#########################################################################################
#################################### CLOUD PROVIDERS ####################################
#########################################################################################
cps:
  aws:
    active: true
    run: 'ruby cps/aws/core.rb'
    full_period_unit: 'h' # options: h(hour), m(minute), s(seconds)

  rackspace:
    active: false
    run: 'ruby cps/rackspace/core.rb'
    full_period_unit: 's'

#########################################################################################
######################################## QUEUES #########################################
#########################################################################################

queues:
  core:
    fanout: 'vadara.core.' #after the dot comes the cp name
  monitor:
    request: 'vadara-monitor-request'
    reply: 'vadara-monitor-reply'
    fanout: 'vadara-monitor'
  scaler:
    request: 'vadara-scaler-request'
    reply: 'vadara-scaler-reply'
    fanout: 'vadara-scaler'

#########################################################################################
####################################### DATABASE ########################################
#########################################################################################

db:
  username: root
  password: root
  host: localhost
  port: 8086
  name: 'vadara-db'
  instances_series: 'instances'
  bootup_times_series: 'bootup_times'
