#########################################################################################
#################################### CLOUD PROVIDERS ####################################
#########################################################################################
cps:
  aws:
    active: false
    run: 'ruby cps/aws/core.rb'

  rackspace:
    active: true
    run: 'ruby cps/rackspace/core.rb'

#########################################################################################
######################################## QUEUES #########################################
#########################################################################################

queues:
  core:
    fanout: 'vadara.core.' #after the dot comes the cp name
  monitor:
    request: 'vadara-monitor-request'
    reply: 'vadara-monitor-reply'
    fanout: 'vadara-monitor'
  scaler:
    request: 'vadara-scaler-request'
    reply: 'vadara-scaler-reply'
    fanout: 'vadara-scaler'
    aws: 'vadara-scaler-aws'

#########################################################################################
####################################### DATABASE ########################################
#########################################################################################

db:
  username: root
  password: root
  host: localhost
  port: 8086
  name: 'vadara-db'
  instances_series: 'instances'
