#########################################################################################
######################################## QUEUES #########################################
#########################################################################################

queues:
  core:
    fanout: 'vadara.core.' #after the dot comes the cp name
  monitor:
    request: 'vadara-monitor-request'
    reply: 'vadara-monitor-reply'
  scaler:
    request: 'vadara-scaler-request'
    reply: 'vadara-scaler-reply'
  decider:
    reply: 'vadara-decider'

#########################################################################################
####################################### DATABASE ########################################
#########################################################################################

db:
  username: root
  password: root
  host: localhost
  port: 8086
  name: 'vadara-db'
  instances_series: 'instances'
  bootup_times_series: 'bootup_times'
